// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPB3zmSmFRlUj-oiHwigecAkuKepbX1I0',
    appId: '1:784508915364:web:64d116cbb223ccdb41e031',
    messagingSenderId: '784508915364',
    projectId: 'ottophix',
    authDomain: 'ottophix.firebaseapp.com',
    storageBucket: 'ottophix.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW483NsBwTjrAVZJ9OkXg8D8VP5uLTSUs',
    appId: '1:784508915364:android:9289cb975fc1e61941e031',
    messagingSenderId: '784508915364',
    projectId: 'ottophix',
    storageBucket: 'ottophix.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA9flAzJ6gSASM-QJgsp8VWTTu5ncT5cY',
    appId: '1:784508915364:ios:62b2e698f8fd2b5a41e031',
    messagingSenderId: '784508915364',
    projectId: 'ottophix',
    storageBucket: 'ottophix.firebasestorage.app',
    iosBundleId: 'com.example.ottophix',
  );
}
